---
name: "Release"
on:
  workflow_dispatch:
  pull_request_target:
    types: [closed]
    branches: [main]
jobs:
  release:
    permissions:
      contents: write
      pull-requests: read
      packages: write       # only needed if building images
      id-token: write       # only needed if creating attestations
      attestations: write   # only needed if creating attestations
      discussions: write    # only needed if creating discussions
    uses: github-community-projects/ospo-reusable-workflows/.github/workflows/release.yaml@e449076963541b0e0a6ee856319a057d3f38cc50
    with:
      publish: true
      goreleaser-config-path: .go-releaser.yaml
      go-version-file: go.mod
      create-attestation: true
      release-config-name: release-drafter.yaml
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
