---
name: "Release"
on:
  workflow_dispatch:
  pull_request_target:
    types: [closed]
    branches: [main]
jobs:
  release:
    permissions:
      contents: write
      pull-requests: read
      id-token: write       # only needed if creating attestations
      attestations: write   # only needed if creating attestations
    uses: github-community-projects/ospo-reusable-workflows/.github/workflows/release.yaml@613657f4f026e3b7086f22ce395ef7d2eb1f8321
    with:
      publish: true
      goreleaser-config-path: .go-releaser.yaml
      go-version-file: go.mod
      create-attestation: true
      release-config-name: release-drafter.yaml
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
